### PR TITLE
wrong example misguide user to catch panic

### PR DESCRIPTION
**Pull request by Wander1024**
Signed-off-by: wander1024 <yawhua1024@gmail.com>

recovery should be placed the first.

#410 
#215

### CODE REVIEW

**Comment by Wander1024** [comment]
@googlebot I signed it!

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Thanks for your contribution :). Sorry for the confusion here.

**Comment by ivanovaleksey** [comment]
With grpc_recovery in the first place I can see nothing in logger just this

```
srv := grpc.NewServer(grpc.UnaryInterceptor(
	grpc_middleware.ChainUnaryServer(
		grpc_recovery.UnaryServerInterceptor(),
		grpc_ctxtags.UnaryServerInterceptor(),
		grpc_zap.UnaryServerInterceptor(zapLogger),
	),
))

 zap/grpclogger.go:92    [transport]transport: loopyWriter.run returning. connection error: desc = "transport is closing"        {"system": "grpc", "grpc_log": true}
 ```
How is it supposed to log a panic occurred?

**Pull request merged**
