### PR TITLE
logging/zap/ctxzap: add shorthand functions

### PR DESCRIPTION
**Pull request by CAFxX**
Adds common shorthand functions. See https://github.com/grpc-ecosystem/go-grpc-middleware/issues/407 for details.

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Could you have a look at cherry-picking this to the v2 branch? It may need some rejigging.

**Comment by CAFxX** [comment]
@johanbrandhorst it seems the whole package is missing in v2. Has it been left out on purpose, or it's simply still to be ported over?

**Comment by johanbrandhorst** [comment]
The logging infrastructure was refactored significantly in v2, but maybe https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/providers/zap/logger.go is the place?

**Comment by CAFxX** [comment]
Yeah saw that, but it seems all of those providers are missing the ctx* subpackage (like ctxzap here). Is it deliberate to not have the context based functionality, or just it hasn't been done yet?

**Comment by johanbrandhorst** [comment]
CC @bwplotka

**Pull request merged**
