### PR TITLE
Added Dependabot

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #275

### CODE REVIEW

**Comment by yashrsharma44** [comment]
Tests are failing due to an unrelated data race. I thought that would have been fixed by this - #354 :worried:

**Comment by iamrajiv** [comment]
@yashrsharma44 I think this can be merged now.

**Review by yashrsharma44 — APPROVED** [review]
LGTM! @johanbrandhorst can we get this merged?

**Comment by bwplotka** [comment]
Let's try it out. Thanks!

**Pull request merged**
