### PR TITLE
add(*): Add filedmask interceptor

### PR DESCRIPTION
**Pull request by linhbkhn95**
## Changes

- Add `fieldmask` interceptor that allow filter response base on client's request intent.
## How to use
`Pre-condition`

You have to add `field_mask` into proto's request like
``` Protobuf
message Request{
  // main fields
  google.protobuf.FieldMask field_mask = 100;
}
```
1. install via go get 

 `go get github.com/grpc-ecosystem/go-grpc-middleware/v2`
`

2. Import and inject into grpc interceptor
The code in your application should be like that:
``` Go
import(
        // ...
        "google.golang.org/grpc"
    	fieldmaskpkg "github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/fieldmask"


)
// ...

func main(){
    var unaryOpts []grpc.UnaryServerInterceptor{
		fieldmaskpkg.UnaryServerInterceptor(fieldmaskpkg.DefaultFilterFunc),
    }
    // Should append others interceptors
}
```
3. Client usage

	 `Protobuf definition`
	 ```Protobuf
	   message GetProductRequest{
	     string id = 1;
	     google.protobuf.FieldMask field_mask = 2;
	   }
	   message Response{
	     message Result{
	        repeated Product products = 1;
	     }
	     Result result = 1;
	   }
	   message Product{
	      string id = 1;
	      string name = 2;
	      string img = 3;
	      decimal price = 4;
	   }
	   
 	```

	Client interaction

	 ``` Go
         func GetProduct(id string) *Product{
		  request := pb.GetProductRequest{
			Id: "axaxaxx",
			FieldMask: &fieldmaskpb.FieldMask{
				Paths: []string{
					"result.products.id", "result.products.name"
				},
			}
		   }
           // ...
         }
	
	 ```
- I have built an individual repo for this idea
https://github.com/linhbkhn95/go-grpc-middleware-field-mask
## Verification

- I wrote tests

### CODE REVIEW

**Comment by linhbkhn95** [comment]
@jpkrohling @bwplotka can you guys give me some suggestions in this PR?

**Comment by johanbrandhorst** [comment]
Hi, this is cool, but I'm not sure it's generically useful enough to be merged into the library. Field masks can be used for a number of different things, not just for filtering fields in a response message. I don't think we want this functionality in the library. Thank you for your PR though!

**Comment by linhbkhn95** [comment]
I know that field masks are not only for filtering responses(partial update). Can I change the package name to fit with this functionality?
@johanbrandhorst

**Comment by johanbrandhorst** [comment]
I just think the functionality is too niche to be generally useful. It's a cool example of how users can implement their own interceptors using the framework in this repo, but I don't know that it's something users will find useful otherwise. You could submit a documentation PR if you want?

**Comment by linhbkhn95** [comment]
` You could submit a documentation PR if you want?`. What is your mean? where is the documentation repo?

**Comment by johanbrandhorst** [comment]
I mean that we could add an example to https://github.com/grpc-ecosystem/go-grpc-middleware/tree/main/examples, something about implementing your own interceptors and use this as an example.

**Pull request closed without merging**
