### PR TITLE
Support for subsystem in grpc prometheus counter and histogram metrics

### PR DESCRIPTION
**Pull request by rohsaini**
## Changes

Introduction of apis: WithSubsystem() and WithHistogramSubsystem()

## Verification
Added new test cases for client and server metrics both.

cd /home/ubuntu/datadisk/CLONES/go-grpc-middleware-subsystem/providers/prometheus && go test -v -race ./...
=== RUN TestClientInterceptorSuite
=== RUN TestClientInterceptorSuite/TestStartedStreamingIncrementsStarted
=== RUN TestClientInterceptorSuite/TestStreamingIncrementsMetrics
=== RUN TestClientInterceptorSuite/TestUnaryIncrementsMetrics
=== RUN TestClientInterceptorSuite/TestWithSubsystem
=== NAME TestClientInterceptorSuite
interceptor_suite.go:154: stopped grpc.Server at: 127.0.0.1:40133
--- PASS: TestClientInterceptorSuite (0.24s)
--- PASS: TestClientInterceptorSuite/TestStartedStreamingIncrementsStarted (0.00s)
--- PASS: TestClientInterceptorSuite/TestStreamingIncrementsMetrics (0.01s)
--- PASS: TestClientInterceptorSuite/TestUnaryIncrementsMetrics (0.00s)
--- PASS: TestClientInterceptorSuite/TestWithSubsystem (0.00s) <<<<<<<<
=== RUN TestServerInterceptorSuite
=== RUN TestServerInterceptorSuite/TestContextCancelledTreatedAsStatus
=== RUN TestServerInterceptorSuite/TestRegisterPresetsStuff
=== RUN TestServerInterceptorSuite/TestStartedStreamingIncrementsStarted
=== RUN TestServerInterceptorSuite/TestStreamingIncrementsMetrics
=== RUN TestServerInterceptorSuite/TestUnaryIncrementsMetrics
=== RUN TestServerInterceptorSuite/TestWithSubsystem
=== NAME TestServerInterceptorSuite
interceptor_suite.go:154: stopped grpc.Server at: 127.0.0.1:38755
--- PASS: TestServerInterceptorSuite (0.73s)
--- PASS: TestServerInterceptorSuite/TestContextCancelledTreatedAsStatus (0.10s)
--- PASS: TestServerInterceptorSuite/TestRegisterPresetsStuff (0.03s)
--- PASS: TestServerInterceptorSuite/TestStartedStreamingIncrementsStarted (0.20s)
--- PASS: TestServerInterceptorSuite/TestStreamingIncrementsMetrics (0.11s)
--- PASS: TestServerInterceptorSuite/TestUnaryIncrementsMetrics (0.00s)
--- PASS: TestServerInterceptorSuite/TestWithSubsystem (0.00s) <<<<<<<<
PASS
ok github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus 1.006s

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Just giving Bartek a chance to review as well before merge.

**Comment by rohsaini** [comment]
@bwplotka Can you please review.

**Comment by johanbrandhorst** [comment]
Thanks for your contribution :)

**Comment by bwplotka** [comment]
Thanks!

**Comment by rohsaini** [comment]
Thanks @johanbrandhorst . Can you please tag it on main branch.

I am using github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus v1.0.0-rc.0 currently.

**Comment by johanbrandhorst** [comment]
I tagged https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/providers%2Fprometheus%2Fv1.0.0, hopefully that works :)

**Comment by rohsaini** [comment]
Thanks. It is available now.

**Pull request merged**
