### PR TITLE
Do not set timeout for stream initialization

### PR DESCRIPTION
**Pull request by DavyJohnes**
## Changes

Details of issue can be found here: https://github.com/grpc-ecosystem/go-grpc-middleware/issues/636

### CODE REVIEW

**Review by johanbrandhorst — COMMENTED** [review]
I'm a bit confused. What is this fixing? Could you link to an issue or a problem you're having?

**Comment by DavyJohnes** [comment]
> I'm a bit confused. What is this fixing? Could you link to an issue or a problem you're having?

Actually I've linked issue, where problem is described. But I guess I had to do it more explicitly. Added it to issue description.

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by johanbrandhorst** [comment]
Thanks for the link, I had just forgotten about it :)

**Comment by DavyJohnes** [comment]
@johanbrandhorst Hi! Is it possible to perform release, so this commit become available for actual use in my code? :)

**Pull request merged**
