### PR TITLE
Add zerolog support to logging

### PR DESCRIPTION
**Pull request by irridia**
Integrates zerolog into go-grpc-middleware/logging.

This is an adaptation of the logrus code but with the Deprecated pieces (that I noticed) removed, and modified for zerolog's mechanisms.

Right now, the imports reference the fork, but would of course be updated before merge. If preferred, I can add ctxzerolog first, but the testing imports also complicate matters. Tests pass, but `make all` is confused because of the imports.

I welcome all feedback!

### CODE REVIEW

**Comment by irridia** [comment]
@googlebot I signed it!

**Comment by bwplotka** [comment]
Amazing!

We love this work, but the idea is to develop on v2. Can you rebase on `v2` branch? We actually redesigned to it should be thousands times easier to integrate new logger :heart: 

What do you think?

You can read more here https://github.com/grpc-ecosystem/go-grpc-middleware/issues/275

**Comment by nashikb** [comment]
> We love this work, but the idea is to develop on v2. Can you rebase on v2 branch? We actually redesigned to it should be thousands times easier to integrate new logger ❤️

Sure, will do. After poking at this code, several of the v2 tasks are <3 to me. :)

**Comment by nashikb** [comment]
What do you think about adding this implementation to v1 *AND* I'll adjust/implement for v2? Seems like people will get the benefit sooner from v1.

**Comment by irridia** [comment]
> We love this work, but the idea is to develop on v2. Can you rebase on v2 branch? We actually redesigned to it should be thousands times easier to integrate new logger ❤️

Sure, will do. After poking at this code, several of the v2 tasks are <3 to me. :)

**Comment by irridia** [comment]
What do you think about adding this implementation to v1 AND I'll adjust/implement for v2? Seems like people will get the benefit sooner from v1.

**Comment by irridia** [comment]
Done: https://github.com/grpc-ecosystem/go-grpc-middleware/pull/299

**Comment by bwplotka** [comment]
> What do you think about adding this implementation to v1 AND I'll adjust/implement for v2? Seems like people will get the benefit sooner from v1.

I think we don't want to focus on v1. It's broken loop to add another 2 thousands lines of code to the library we want only support for bugfixes (: Also you had thousands benefits from switching to new version of go-grpc, so hopefully the effect of supporting zerolog only on `v2` will give even more motivation for initial pain of migrating (:

**Comment by irridia** [comment]
> Also you had thousands benefits from switching to new version of go-grpc, so hopefully the effect of supporting zerolog only on `v2` will give even more motivation for initial pain of migrating (:

Is v2 at the point where it's a fully-functional replacement for v1? I agree if anyone can switch to v2 now.

**Comment by bwplotka** [comment]
Let's close this one as v2 was merged: https://github.com/grpc-ecosystem/go-grpc-middleware/pull/299

**Pull request closed without merging**
