### PR TITLE
Client-side rate limit interceptors (#520)

### PR DESCRIPTION
**Pull request by rahulkhairwar**
Original Issue: [here](https://github.com/grpc-ecosystem/go-grpc-middleware/issues/520)

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Looks solid, thanks!

Want to rebase? Otherwise LGTM!

**Comment by rahulkhairwar** [comment]
Hi @bwplotka !
I just rebased with the latest `v2`.
There's a failing check (lint issue, coming from: [#544](https://github.com/grpc-ecosystem/go-grpc-middleware/pull/544)).
I believe once that is fixed, we can merge this PR too!
Lmk if you need anything from me, cheers! :)

**Comment by rahulkhairwar** [comment]
Hey @bwplotka , can we merge this PR? There was a pending linter check which was failing earlier, I fixed it (rebased with `v2`).

**Comment by bwplotka** [comment]
Will check tomorrow, thanks!

**Review by bwplotka — APPROVED** [review]
Nice, amazing. Thanks!

**Comment by rahulkhairwar** [comment]
Yup, rebased with `main` and reopened (https://github.com/grpc-ecosystem/go-grpc-middleware/pull/599/files).

**Pull request closed without merging**
