### PR TITLE
Added logr as logging Library provider

### LINKED ISSUE #430: v2: logging provider: klog/v2
As most of k8s related tools are using klog as a standarad logging tools, it's great if we consider adding klog/v2 provider in v2 natively.

### LINKED ISSUE #473: Support for klog as logging middleware
We use github.com/kubernetes/klog extensively in many go projects as the logging library. 

Possible to get it in here as a middleware. Would love to add support if it is possible.

### PR DESCRIPTION
**Pull request by mcdoker18**
Closes #473
Closes #430

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
This looks great to me, but would love input from @bwplotka.

**Comment by mcdoker18** [comment]
@johanbrandhorst Can you please help me with the failed linter job?

```
cannot lint and format files: you have unstaged changes.
M	providers/logr/examples_test.go
M	providers/logr/logger.go
M	providers/logr/logger_test.go
Please commit or stash them.
```

If it's a flaky job I can't restart it.

**Comment by johanbrandhorst** [comment]
I'm guessing it's just a bad error and it's trying to tell us that there was a file formatting diff. Can you try formatting those files?

**Comment by mcdoker18** [comment]
> I'm guessing it's just a bad error and it's trying to tell us that there was a file formatting diff. Can you try formatting those files?

Done, thanks!

**Review by bwplotka — APPROVED** [review]
👍🏽

**Comment by bwplotka** [comment]
Thanks!

**Pull request merged**
