### PR TITLE
Update provider/kit

### PR DESCRIPTION
**Pull request by metalmatze**
There were incompatibilities when requiring the latest commit for the main module. 
Hence I've added the ```
replace github.com/grpc-ecosystem/go-grpc-middleware/v2 => ../..```
similar to what the provider/openmetrics does. 

Now the only problem is that I'm not 100% sure how the removal of the tags package is supposed to work here. Additionally, the `payloadDecider` needs to be fixed too. I wasn't able to find exactly which type implements that.

/cc @bwplotka

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Thanks 👍🏽

**Comment by bwplotka** [comment]
Plus linter is failing

**Comment by metalmatze** [comment]
I'm not sure if I correctly removed the `tags` package if there was something I missed or it really was just about deleting the lines in this PR?

**Comment by bwplotka** [comment]
I don't know, I would need to look into the details. This PR looks like a good direction at least 🙃

**Pull request merged**
