### PR TITLE
feat: Initialized Go gRPC Middleware docs site

### PR DESCRIPTION
**Pull request by iamrajiv**
## Description

Fixes: #460

- [x] Initialized the docs site with [Just the Docs](https://github.com/pmarsceill/just-the-docs) Jekyll theme.
- [x] Refactored README.

### CODE REVIEW

**Comment by iamrajiv** [comment]
Hi, @bwplotka @johanbrandhorst @yashrsharma44, I have initialized the docs. Also, we need to add a new GitHub token to the repository with the name `JEKYLL_GITHUB_TOKEN` because we need it to build the site automatically whenever there is a change in the docs folder.

**Comment by bwplotka** [comment]
Hi, 

Thank you for this contribution, but I think we would love to choose a technology that is closer to what maintainers know about. The reason is that we need to maintain it over time. But generally, the idea to have a website is amazing! We recently used https://github.com/bwplotka/mdox and Hugo for this job, so if you want to help, let's aim for that instead of jekyll & co. 

You can learn about mdox here https://www.bwplotka.dev/2021/mdox

**Comment by bwplotka** [comment]
Also this has to be on `v2` if we still wants this.

**Comment by bwplotka** [comment]
Closing, unless you want to continue on this, we can then reopen.

**Pull request closed without merging**
