### PR TITLE
Tags from metadata

### PR DESCRIPTION
**Pull request by lmm**
This continues https://github.com/grpc-ecosystem/go-grpc-middleware/pull/97 by addressing feedback to replace `RequestFieldExtractorFunc` with `RequestFieldExtractorWithContextFunc`.

cc @graphaelli

### CODE REVIEW

**Comment by lmm** [comment]
I signed it!

**Comment by lmm** [comment]
@graphaelli are you ok with your commit being used in this PR?

**Comment by graphaelli** [comment]
Certainly, thanks for picking this up!

**Comment by pacoguzman** [comment]
Good be great to have this released

**Comment by johanbrandhorst** [comment]
This is a backward-compatibility breaking change, any chance we could just duplicate the methods for now? We are considering a v2 where the old one could be removed, but I don't think we want to break compatibility right now.

**Comment by zifter** [comment]
Any news?

**Comment by sejin-P** [comment]
I want to use feature which can log grpc metadata with request or response in grpc streaming server. However, unfortunately, this pr was closed. I understood that it has backward-compatibility breaking changes, so I don't want to apply this feature with forking because of maintenance. Is there anyone has idea to resolve this?

**Comment by johanbrandhorst** [comment]
We've rewritten the code quite a lot in the v2 branch, maybe take a look and see if it does what you want already?

**Comment by sejin-P** [comment]
@johanbrandhorst thank you for your response! I'm gonna see it and if the feature I wanted not exist, I'll make some pull requests. Thank you!

**Pull request closed without merging**
