### PR TITLE
Improve logging/*/doc.go

### PR DESCRIPTION
**Pull request by matiasanaya**
Add 'grpc.request.deadline' example and fix typo.

### CODE REVIEW

**Comment by matiasanaya** [comment]
I signed it!

**Comment by domgreen** [comment]
Thanks for the PR, would you mind running `make doc` or `make` this will generate the md files for this change. 

Will try and make this more obvious somewhere. 👍

**Comment by matiasanaya** [comment]
@domgreen not sure if it's my setup or change related but the whitespace of the `*.md` files has changed significantly. I'm running `make docs` locally on mac os.

**Comment by domgreen** [comment]
@matiasanaya let me run your change locally and see what I get will get back to you this afternoon

**Comment by domgreen** [comment]
I actually think this is just correcting the extra tab, don't think thats an issue tbh.

**Comment by domgreen** [comment]
@matiasanaya ping

**Comment by matiasanaya** [comment]
Sorry @domgreen, was on leave :)

I believe this PR is fine and in fact corrects a previous alignment issue.

If you look at the [current doc](https://raw.githubusercontent.com/grpc-ecosystem/go-grpc-middleware/master/logging/logrus/DOC.md) the two `json` blocks (_Server Interceptor_ and _Payload Interceptor_) seem to line up differently. Now if you compare that with [this PR's doc](https://raw.githubusercontent.com/matiasanaya/go-grpc-middleware/5c174943de9621eed69caac6ae0298325b0fee47/logging/logrus/DOC.md) the two `json` blocks line up perfectly.

Thoughts?

**Comment by matiasanaya** [comment]
Resolved conflicts

**Pull request merged**
