### PR TITLE
Spelling/grammar corrections for validator docs

### PR DESCRIPTION
**Pull request by thurt**

### CODE REVIEW

**Comment by thurt** [comment]
I signed it!

**Comment by domgreen** [comment]
Is this documentation not generated from the `doc.go` file? I think the general pattern in the repo is to change the go docs and generate the README can we just check if that is used here and if not bring in line with the other documentation. :smile:

**Comment by domgreen** [comment]
So just checking this, would you mind making the docs conform to how the remaining middleware are documented? 
* `README.md` should be a symlink to `DOC.md`
* make the change in `doc.go`
* run `make doc` to re-generate the documentation.

**Comment by domgreen** [comment]
@thurt ping

**Comment by mwitkow** [comment]
It is, @thurt please update the `doc.go` as well.

**Comment by thurt** [comment]
@domgreen @mwitkow  thanks for the instructions, i remade the commit. please look at the changes and let me know!

**Pull request merged**
