### PR TITLE
Added Dependabot

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #275

### CODE REVIEW

**Review by yaronius — APPROVED** [review]
Looking forward to v2 branch release 👍

**Comment by bwplotka** [comment]
Can we add this to v2 branch then? 🤗

**Comment by iamrajiv** [comment]
@bwplotka Sure. Do I have to make a new PR against the v2 branch?

**Comment by bwplotka** [comment]
No, you can just rebase on `v2`

**Comment by iamrajiv** [comment]
@bwplotka I was getting merge conflicts error in my local system while rebasing I think I messed up with the branches. I have created a new PR #376.

**Pull request closed without merging**
