### PR TITLE
Added method to create your own unary request handler

### PR DESCRIPTION
**Pull request by Apologiz**

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
What is the purpose of this PR? Maybe you could create an issue first and explain your problem?

**Comment by Apologiz** [comment]
This PR allows you to do custom request logging in opentracer (jaeger).
I need to write a full request in the tracer, it solves my need a little refinement  :)

Example:
```go
var reqHandler = func(span opentracing.Span, req interface{}) {
  if msg, ok := req.(proto.Message); ok {
    if body, err := serializer.MarshalToString(msg); err == nil {
      span.LogFields(otlog.String("body", body))
    }
  }
}
// ...
grpc_opentracing.UnaryServerInterceptor(
  grpc_opentracing.WithTracer(opentracing.GlobalTracer()),
  grpc_opentracing.WithUnaryRequestHandlerFunc(reqHandler),
),
```

**Comment by Apologiz** [comment]
Yes, I'll do it)

**Comment by Apologiz** [comment]
@googlebot I consent

**Comment by Apologiz** [comment]
@googlebot I consent.

**Pull request merged**
